# See https://pre-commit.com/hooks.html for more pre-commit hooks
# See https://prek.j178.dev/builtin/ for more prek hooks and prek setup
repos:
  - repo: meta
    hooks:
      - id: check-hooks-apply
      - id: check-useless-excludes

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    - id: check-added-large-files
      args: [ "--maxkb=200" ]
    - id: check-json
    - id: check-toml
    - id: check-xml
    - id: check-yaml
      args:
        - --unsafe
    - id: detect-private-key
    # This check follows the definition of a text file in POSIX: IEEE Std 1003.1-2017
    # https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap03.html#tag_03_403
    # Rule: a text file shall end with a <newline> character '\n'.
    # Keep this check in sync with .gitattributes and ruff settings.
    - id: end-of-file-fixer
    - id: mixed-line-ending
      args: [ --fix=lf ]
    - id: trailing-whitespace
      args: [--markdown-linebreak-ext=md]

  - repo: local
    hooks:
      - id: local-codespell
        name: codespell
        entry: uv run codespell --write-changes --ignore-words=.codespell-ignore-words
        language: unsupported
        require_serial: true
        pass_filenames: true
        types_or: [ text ]

      - id: local-check-github-workflows
        name: check GitHub workflows
        entry: uv run check-jsonschema --verbose --builtin-schema vendor.github-workflows
        language: unsupported
        require_serial: true
        pass_filenames: true
        files: ^\.github/workflows/.*\.ya?ml$

      - id: local-check-github-actions
        name: check GitHub actions
        entry: uv run check-jsonschema --verbose --builtin-schema vendor.github-actions
        language: unsupported
        require_serial: true
        pass_filenames: true
        files: (^|/)(action\.ya?ml)$

#      - id: local-ruff-check
#        name: ruff check
#        entry: uv run ruff check --force-exclude --fix --exit-non-zero-on-fix
#        require_serial: true
#        language: unsupported
#        pass_filenames: true
#        types: [ python ]

      - id: local-ruff-format
        name: ruff format
        entry: uv run ruff format --force-exclude --exit-non-zero-on-format
        require_serial: true
        language: unsupported
        pass_filenames: true
        types: [ python ]

      - id: local-pyproject-fmt
        name: pyproject-fmt
        entry: uv run pyproject-fmt
        language: unsupported
        require_serial: true
        pass_filenames: true
        files: ^(.*/)?pyproject\.toml$

#      - id: local-ty
#        name: ty check
#        entry: uv run ty check fastapi
#        require_serial: true
#        language: unsupported
#        pass_filenames: false

      - id: local-uv-lock
        name: uv lock check
        entry: uv run uv lock --check
        language: unsupported
        pass_filenames: false
        require_serial: false
        always_run: true

      - id: local-zizmor
        name: zizmor
        language: python
        entry: uv run zizmor .
        require_serial: true
        pass_filenames: false
        files: ^\.github\/workflows\/
