version = 1
disable_existing_loggers = false

###########################
# FILTERS
###########################

[filters.request_context]
"()" = "template_app.core.logging.filters.RequestContextFilter"

###########################
# FORMATTERS
###########################

[formatters.json]
class = "pythonjsonlogger.jsonlogger.JsonFormatter"

format = """
%(asctime)s
%(levelname)s
%(name)s
%(message)s
%(request_id)s
%(method)s
%(path)s
"""

###########################
# HANDLERS
###########################

[handlers.stdout]
class = "logging.StreamHandler"
formatter = "json"
stream = "ext://sys.stdout"

###########################
# LOGGERS
###########################

[loggers.uvicorn]
handlers = ["stdout"]
level = "INFO"
propagate = false

[loggers."uvicorn.error"]
handlers = ["stdout"]
level = "INFO"
propagate = false

[loggers."uvicorn.access"]
handlers = ["stdout"]
level = "INFO"
propagate = false

[loggers.fastapi]
handlers = ["stdout"]
level = "INFO"
propagate = false

[loggers.template_app]
handlers = ["stdout"]
level = "INFO"
propagate = false

###########################
# ROOT
###########################

[root]
handlers = ["stdout"]
level = "INFO"
