apiVersion: apps/v1
kind: Deployment
metadata:
  name: template-kafka
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: worker
          image: template-app:latest
          command: ["python", "-m", "template_app.cli", "kafka"]
