FROM python:3.11-slim

# install uv
RUN pip install uv

WORKDIR /app

# copy only lockfile + workspace metadata
COPY pyproject.toml uv.lock ./
COPY packages ./packages
COPY services/backend-api ./services/backend-api

# install deps ONLY for backend-api
RUN uv sync --frozen --no-dev --package backend-api

# Start with hot reload
CMD ["uv", "run", "uvicorn", "app.main:app", "--reload", "--host", "0.0.0.0", "--port", "8000"]

