name: CI
run-name: >
  ${{ github.event_name == 'pull_request'
      && format('🔀 PR #{0} by {1} - {2} 🚀',
                github.event.pull_request.number,
                github.event.pull_request.user.login,
                github.ref_name)
      || startsWith(github.ref, 'refs/tags/')
      && format('🏷️ Tag {0} 🚀', github.ref_name)
      || github.event_name == 'push'
      && format('⬆️ Push to {0} 🚀', github.ref_name)
      || github.event_name == 'release'
      && format('📦 Release {0} 🚀', github.ref_name)
      || github.event_name == 'workflow_dispatch'
      && '🧑‍💻 Manual run 🚀'
      || format('🚀 CI for {0}', github.ref_name)
  }}

on:
  merge_group:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
  push:
    branches:
      - main
#    tags:
#      - v*

env:
  FORCE_COLOR: 3 # Request colored output from tools (e.g. eslint, prettier, markdownlint) supporting FORCE_COLOR
  PRE_COMMIT_COLOR: always
  UV_COLOR: always

  UV_CACHE_DIR: /tmp/.uv-cache
  PRE_COMMIT_HOME: /tmp/.pre-commit-cache


permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  linters:
    name: 🧹 Linters
    runs-on: ubuntu-24.04

    steps:
      - name: 📥 Checkout the repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: 🧮 Create cache prefix
        run: |
            OS_NAME=$(uname -s)
            OS_ARCH=$(uname -m)
            OS_KERNEL=$(uname -r)
            OS_BUILD=$(uname -v | awk '{print $1}')

            echo "OS_NAME=$OS_NAME" >> $GITHUB_ENV
            echo "OS_ARCH=$OS_ARCH" >> $GITHUB_ENV
            echo "OS_KERNEL=$OS_KERNEL" >> $GITHUB_ENV
            echo "OS_BUILD=$OS_BUILD" >> $GITHUB_ENV

            echo "CACHE_PREFIX=${OS_NAME}-${OS_ARCH}-${OS_KERNEL}-${OS_BUILD}" >> $GITHUB_ENV

      - name: 💾 Restore pre-commit cache
        uses: actions/cache/restore@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        id: restore-pre-commit-cache
        with:
          path: ${{ env.PRE_COMMIT_HOME }}
          key: pre-commit-${{ env.CACHE_PREFIX }}-${{ hashFiles('.pre-commit-config.yaml') }}
          restore-keys: pre-commit-

      - name: 🔧 Setup Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version-file: ".python-version"

      - name: 🔧 Setup uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
        with:
          version-file: "pyproject.toml"
          activate-environment: "false"
          enable-cache: "true"
          restore-cache: "true"
          save-cache: "true"
          cache-suffix: ""  # Suffix for the cache key
          cache-local-path: ${{ env.UV_CACHE_DIR }}
          prune-cache: "false"

      - name: 🔧 Setup .venv
        run: uv sync --frozen --group dev

      - name: 🧪 Run pre-commit checks # only check the changed files
        # TODO: change this to check all files
        run: |
          uv run pre-commit run \
          --from-ref "${{ github.event.pull_request.base.sha }}" \
          --to-ref   "${{ github.event.pull_request.head.sha }}"

      - name: 📝 Print environment summary
        run: |
          echo "📝 OS:"; uname -a
          echo "📝 UV:"; uv --version ; which uv
          echo "📝 UV_CACHE_DIR:"; du -sh "${{ env.UV_CACHE_DIR }}"
          echo "📝 PYTHON:"; uv run python --version ; uv run which python
          echo "📝 PYTHON .venv SIZE:"; du -sh .venv
          echo "📝 PRE-COMMIT:"; uv run pre-commit --version ; uv run which pre-commit
          echo "📝 PRE_COMMIT_HOME CACHE DIR:"; du -sh "${{ env.PRE_COMMIT_HOME }}"

      - name: 💾 Save pre-commit cache
        id: save-pre-commit-cache
        if: github.ref == 'refs/heads/main' &&
          steps.restore-pre-commit-cache.outputs.cache-hit != 'true'
        uses: actions/cache/save@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: ${{ env.PRE_COMMIT_HOME }}
          key: ${{ steps.restore-pre-commit-cache.outputs.cache-primary-key }}

  check:  # This job does nothing and is only used for the branch protection
    name: 🏁 Check
    if: always()
    needs:
      - linters
    runs-on: ubuntu-24.04
    timeout-minutes: 1

    steps:
      - name: 🏁 Decide whether the needed jobs succeeded or failed
        uses: re-actors/alls-green@05ac9388f0aebcb5727afa17fcccfecd6f8ec5fe # v1.2.2
        with:
          jobs: ${{ toJSON(needs) }}
